package org.zuel.innovation.common.module;

import org.zuel.innovation.common.module.base.BaseBill;
import org.zuel.innovation.common.module.base.BaseLoginInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Bill extends BaseBill<Bill> {
	public static final Bill dao = new Bill().dao();
}
