package org.zuel.innovation.common.module;

import org.zuel.innovation.common.module.base.BaseLoginInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LoginInfo extends BaseLoginInfo<LoginInfo> {
	public static final LoginInfo dao = new LoginInfo().dao();
}
