package org.zuel.innovation.common.module;

import org.zuel.innovation.common.module.base.BaseSession;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Session extends BaseSession<Session> {
	public static final Session dao = new Session().dao();
}
