package org.zuel.innovation.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBill<M extends BaseBill<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}
	
	public void setIsDeleted(java.lang.String isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	public java.lang.String getIsDeleted() {
		return getStr("is_deleted");
	}
	
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}
	
	public void setIdentification(java.lang.String identification) {
		set("identification", identification);
	}
	
	public java.lang.String getIdentification() {
		return getStr("identification");
	}
	
	public void setSumLesson(java.lang.String sumLesson) {
		set("sum_lesson", sumLesson);
	}
	
	public java.lang.String getSumLesson() {
		return getStr("sum_lesson");
	}
	
	public void setSumLessonTime(java.lang.String sumLessonTime) {
		set("sum_lesson_time", sumLessonTime);
	}
	
	public java.lang.String getSumLessonTime() {
		return getStr("sum_lesson_time");
	}
	
	public void setSumMorningLesson(java.lang.String sumMorningLesson) {
		set("sum_morning_lesson", sumMorningLesson);
	}
	
	public java.lang.String getSumMorningLesson() {
		return getStr("sum_morning_lesson");
	}
	
	public void setSumEveningLesson(java.lang.String sumEveningLesson) {
		set("sum_evening_lesson", sumEveningLesson);
	}
	
	public java.lang.String getSumEveningLesson() {
		return getStr("sum_evening_lesson");
	}
	
	public void setMostBuliding(java.lang.String mostBuliding) {
		set("most_buliding", mostBuliding);
	}
	
	public java.lang.String getMostBuliding() {
		return getStr("most_buliding");
	}
	
	public void setMostBulidingLesson(java.lang.String mostBulidingLesson) {
		set("most_buliding_lesson", mostBulidingLesson);
	}
	
	public java.lang.String getMostBulidingLesson() {
		return getStr("most_buliding_lesson");
	}
	
	public void setMostClassroom(java.lang.String mostClassroom) {
		set("most_classroom", mostClassroom);
	}
	
	public java.lang.String getMostClassroom() {
		return getStr("most_classroom");
	}
	
	public void setMostClassroomLesson(java.lang.String mostClassroomLesson) {
		set("most_classroom_lesson", mostClassroomLesson);
	}
	
	public java.lang.String getMostClassroomLesson() {
		return getStr("most_classroom_lesson");
	}
	
	public void setMostConsumeMoneyCanteen(java.lang.String mostConsumeMoneyCanteen) {
		set("most_consume_money_canteen", mostConsumeMoneyCanteen);
	}
	
	public java.lang.String getMostConsumeMoneyCanteen() {
		return getStr("most_consume_money_canteen");
	}
	
	public void setMostConsumeCanteenMoney(java.lang.String mostConsumeCanteenMoney) {
		set("most_consume_canteen_money", mostConsumeCanteenMoney);
	}
	
	public java.lang.String getMostConsumeCanteenMoney() {
		return getStr("most_consume_canteen_money");
	}
	
	public void setSumCharge(java.lang.String sumCharge) {
		set("sum_charge", sumCharge);
	}
	
	public java.lang.String getSumCharge() {
		return getStr("sum_charge");
	}
	
	public void setMostConsumeMoneyCanteenDate(java.lang.String mostConsumeMoneyCanteenDate) {
		set("most_consume_money_canteen_date", mostConsumeMoneyCanteenDate);
	}
	
	public java.lang.String getMostConsumeMoneyCanteenDate() {
		return getStr("most_consume_money_canteen_date");
	}
	
	public void setMostConsumeMoneyCanteenOneday(java.lang.String mostConsumeMoneyCanteenOneday) {
		set("most_consume_money_canteen_oneday", mostConsumeMoneyCanteenOneday);
	}
	
	public java.lang.String getMostConsumeMoneyCanteenOneday() {
		return getStr("most_consume_money_canteen_oneday");
	}
	
	public void setSumWebTime(java.lang.String sumWebTime) {
		set("sum_web_time", sumWebTime);
	}
	
	public java.lang.String getSumWebTime() {
		return getStr("sum_web_time");
	}
	
	public void setSumWebFlow(java.lang.String sumWebFlow) {
		set("sum_web_flow", sumWebFlow);
	}
	
	public java.lang.String getSumWebFlow() {
		return getStr("sum_web_flow");
	}
	
	public void setLongestWebUseTimestamp(java.lang.String longestWebUseTimestamp) {
		set("longest_web_use_timestamp", longestWebUseTimestamp);
	}
	
	public java.lang.String getLongestWebUseTimestamp() {
		return getStr("longest_web_use_timestamp");
	}
	
	public void setLongestWebUse(java.lang.String longestWebUse) {
		set("longest_web_use", longestWebUse);
	}
	
	public java.lang.String getLongestWebUse() {
		return getStr("longest_web_use");
	}
	
	public void setLastestWebLogin(java.lang.String lastestWebLogin) {
		set("lastest_web_login", lastestWebLogin);
	}
	
	public java.lang.String getLastestWebLogin() {
		return getStr("lastest_web_login");
	}
	
	public void setLibraryAppointmentTime(java.lang.String libraryAppointmentTime) {
		set("library_appointment_time", libraryAppointmentTime);
	}
	
	public java.lang.String getLibraryAppointmentTime() {
		return getStr("library_appointment_time");
	}
	
	public void setLibraryAppointmentTimeRank(java.lang.String libraryAppointmentTimeRank) {
		set("library_appointment_time_rank", libraryAppointmentTimeRank);
	}
	
	public java.lang.String getLibraryAppointmentTimeRank() {
		return getStr("library_appointment_time_rank");
	}
	
	public void setSumAppointment(java.lang.String sumAppointment) {
		set("sum_appointment", sumAppointment);
	}
	
	public java.lang.String getSumAppointment() {
		return getStr("sum_appointment");
	}
	
	public void setSumAppointmentRank(java.lang.String sumAppointmentRank) {
		set("sum_appointment_rank", sumAppointmentRank);
	}
	
	public java.lang.String getSumAppointmentRank() {
		return getStr("sum_appointment_rank");
	}
	
	public void setEndAchievement(java.lang.String endAchievement) {
		set("end_achievement", endAchievement);
	}
	
	public java.lang.String getEndAchievement() {
		return getStr("end_achievement");
	}
	
}
