package org.zuel.innovation.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSession<M extends BaseSession<M>> extends Model<M> implements IBean {

	/**
	 * 自增主键
	 */
	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	/**
	 * 自增主键
	 */
	public java.math.BigInteger getId() {
		return get("id");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreatedTime(java.util.Date createdTime) {
		set("created_time", createdTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreatedTime() {
		return get("created_time");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdatedTime(java.util.Date updatedTime) {
		set("updated_time", updatedTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdatedTime() {
		return get("updated_time");
	}
	
	/**
	 * 是否删除（0-没有删除；1-已经删除）
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 是否删除（0-没有删除；1-已经删除）
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	/**
	 * 学号
	 */
	public void setUserId(java.lang.String userId) {
		set("user_id", userId);
	}
	
	/**
	 * 学号
	 */
	public java.lang.String getUserId() {
		return getStr("user_id");
	}
	
	/**
	 * 统一认证信息
	 */
	public void setSessionId(java.lang.String sessionId) {
		set("session_id", sessionId);
	}
	
	/**
	 * 统一认证信息
	 */
	public java.lang.String getSessionId() {
		return getStr("session_id");
	}
	
	/**
	 * 登录类型
	 */
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	/**
	 * 登录类型
	 */
	public java.lang.Integer getType() {
		return getInt("type");
	}
	
	public void setSex(java.lang.Integer sex) {
		set("sex", sex);
	}
	
	public java.lang.Integer getSex() {
		return getInt("sex");
	}
	
}
